<?php
session_name(SESS_NAME);
session_start();

define('MAIN', 1);

require_once('./define_config.php');
require_once('./function_profil.php');

session_name(SESS_NAME);
session_start();
$link = sql_connect(SQL_HOST, SQL_USER, SQL_PASSWD);
sql_select_db(SQL_DB, $link);
header(HEADER_CONTENT_TYPE);
if ($_GET[DEBUG])
  printf(XML_HEADER, XML_NO_TEMPLATE);
else
  printf(XML_HEADER, XML_TEMPLATE);
printf(PROFIL_BEGIN);
printf(PROFIL_FIELD_TITLE, PROFIL_POST_TITLE);
printf(PROFIL_FIELD_LOCATION, PROFIL_POST_LOCATION);
printf(PROFIL_FIELD_NAME, PROFIL_POST_NAME);
printf(PROFIL_FIELD_FNAME, PROFIL_POST_FNAME);
printf(PROFIL_FIELD_FPHONE, PROFIL_POST_FPHONE);
printf(PROFIL_FIELD_MPHONE, PROFIL_POST_MPHONE);
printf(PROFIL_FIELD_ADDRESS, PROFIL_POST_ADDRESS);
printf(PROFIL_VALUE_TITLE, $_POST[PROFIL_POST_TITLE]);
printf(PROFIL_VALUE_LOCATION, $_POST[PROFIL_POST_LOCATION]);
printf(PROFIL_VALUE_NAME, $_POST[PROFIL_POST_NAME]);
printf(PROFIL_VALUE_FNAME, $_POST[PROFIL_POST_FNAME]);
printf(PROFIL_VALUE_FPHONE, $_POST[PROFIL_POST_FPHONE]);
printf(PROFIL_VALUE_MPHONE, $_POST[PROFIL_POST_MPHONE]);
printf(PROFIL_VALUE_ADDRESS, $_POST[PROFIL_POST_ADDRESS]);
if ($_POST[PROFIL_POST_NAME])
  {
    /*
    if (!$_POST[PROFIL_POST_PASSWD])
      printf(XML_ERROR, PROFIL_ERROR_PASSWD_NOTFOUND);
    else if (!$_POST[PROFIL_POST_REPASSWD])
      printf(XML_ERROR, PROFIL_ERROR_REPASSWD_NOTFOUND);
    else if (!$_POST[PROFIL_POST_EMAIL])
      printf(XML_ERROR, PROFIL_ERROR_EMAIL_NOTFOUND);
    else
      $created = usr_add();
    */
  }
printf(PROFIL_END);
printf(XML_FOOTER);
sql_close($link);

?>