<?xml version="1.0" encoding="iso-8859-1"?>

<xsl:stylesheet version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:import href="./template/root.xsl" />
  <xsl:import href="./template/header.xsl" />
  <xsl:import href="./template/body.xsl" />
  <xsl:import href="./template/footer.xsl" />
  <xsl:import href="./template/home.xsl" />
  <xsl:import href="./template/connect.xsl" />
  <xsl:import href="./template/create.xsl" />
  <xsl:import href="./template/profil.xsl" />
  <xsl:import href="./template/activity.xsl" />
  <xsl:import href="./template/activity_window.xsl" />
  <xsl:import href="./template/activity_work.xsl" />
  <xsl:import href="./template/information_activity.xsl" />
  <xsl:import href="./template/add_activity.xsl" />
  <xsl:import href="./template/member_activity.xsl" />
  <xsl:import href="./template/error.xsl" />
  <xsl:import href="./template/mesg.xsl" />
  <xsl:import href="./template/warning.xsl" />
  <xsl:import href="./template/project.xsl" />
  <xsl:import href="./template/project_window.xsl" />
  <xsl:import href="./template/add_project.xsl" />
  <xsl:import href="./template/member_project.xsl" />
  <xsl:import href="./template/information_project.xsl" />
  <xsl:import href="./template/project_member_dategraph.xsl" />
  <xsl:import href="./template/field_location.xsl" />
  <xsl:import href="./template/field_title.xsl" />
  <xsl:import href="./template/date.xsl" />
  <xsl:import href="./template/date_start.xsl" />
  <xsl:import href="./template/date_end.xsl" />
  <xsl:import href="./template/administration.xsl" />
  <xsl:import href="./template/member.xsl" />
  <xsl:import href="./template/information_dependance_activity.xsl" />
  <xsl:import href="./template/passwd.xsl" />
  <xsl:import href="./template/gantt.xsl" />
  <xsl:import href="./template/agenda.xsl" />
</xsl:stylesheet>
